#!/command/with-contenv bash
# shellcheck shell=bash

CONFIG_FILE="/config/config.yaml"

[ ! -f "${CONFIG_FILE}" ] || exit 0

echo "Generate act_runner configuration template: ${CONFIG_FILE}"

s6-setuidgid abc \
  bash -c "act_runner generate-config > "${CONFIG_FILE}""