#!/command/with-contenv bash
# shellcheck shell=bash

. /opt/lib/lib.sh

main () {
  local instance
  local instances

  instances=$(get_gitea_runner_instance_count)

  for instance in $(seq 0 $((${instances} - 1)) ); do
    local config_file
    if [ $instance = 0 ]; then
      pushd /config > /dev/null
      config_file="/config/config.yaml"
    else
      s6-setuidgid abc mkdir -p "/config/instance_${instance}"
      pushd "/config/instance_${instance}" > /dev/null
      config_file="/config/instance_${instance}/config.yaml"
    fi

    if [ ! -f "${config_file}" ]; then
      info "Generate gitea-runner configuration template: ${config_file}"
      s6-setuidgid abc \
        bash -c "gitea-runner generate-config > "${config_file}""
      cat "${config_file}"
    fi

    popd > /dev/null
  done
}

main