#!/command/with-contenv bash
# shellcheck shell=bash

export HOME=$(realpath ~abc)
export XDG_DATA_HOME="${HOME}"

: ${DOCUUM_ARGS:="--threshold 80GB"}

exec s6-setuidgid abc \
  /usr/local/bin/docuum ${DOCUUM_ARGS}